import keyword
key=keyword.kwlist
common_html_tags = ['html', 'head', 'title', 'base', 'link', 'meta', 'style', 'script', 'noscript', 
                    'body', 'section', 'nav', 'article', 'aside', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 
                    'header', 'footer', 'address', 'main', 'p', 'hr', 'pre', 'blockquote', 'ol', 'ul', 
                    'li', 'dl', 'dt', 'dd', 'figure', 'figcaption', 'div', 'a', 'em', 'strong', 'small', 
                    's', 'cite', 'q', 'dfn', 'abbr', 'data', 'time', 'code', 'var', 'samp', 'kbd', 'sub', 
                    'sup', 'i', 'b', 'u', 'mark', 'ruby', 'rt', 'rp', 'bdi', 'bdo', 'span', 'br', 'wbr', 
                    'ins', 'del', 'img', 'iframe', 'embed', 'object', 'param', 'video', 'audio', 'source', 
                    'track', 'canvas', 'map', 'area', 'svg', 'math', 'table', 'caption', 'colgroup', 'col', 
                    'tbody', 'thead', 'tfoot', 'tr', 'td', 'th', 'form', 'fieldset', 'legend', 'label', 
                    'input', 'button', 'select', 'datalist', 'optgroup', 'option', 'textarea', 'output', 
                    'progress', 'meter', 'details', 'summary', 'menu', 'menuitem', 'dialog']
common_python_functions = [
    "print",
    "input",
    "len",
    "range",
    "int",
    "str",
    "float",
    "list",
    "tuple",
    "dict",
    "set",
    "sorted",
    "min",
    "max",
    "sum",
    "abs",
    "round",
    "zip",
    "enumerate",
    "any",
    "all",
    "map",
    "filter",
    "lambda functions",
    "isinstance",
    "type",
    "dir",
    "getattr",
    "setattr",
    "hasattr",
    "open",
    "close",
    "read",
    "write",
    "append",
    "extend",
    "pop",
    "remove",
    "clear",
    "join",
    "split",
    "replace",
    "strip",
    "lower",
    "upper",
    "capitalize",
    "title",
    "format",
    "format_map",
    "isalpha",
    "isdigit",
    "isnumeric",
    "isalnum",
    "isspace",
    "startswith",
    "endswith",
    "index",
    "find",
    "count",
    "isinstance",
    "type",
    "dir",
    "getattr",
    "setattr",
    "hasattr",
    "open",
    "close",
    "read",
    "write",
    "append",
    "extend",
    "pop",
    "remove",
    "clear",
    "join",
    "split",
    "replace",
    "strip",
    "lower",
    "upper",
    "capitalize",
    "title",
    "format",
    "format_map",
    "isalpha",
    "isdigit",
    "isnumeric",
    "isalnum",
    "isspace",
    "startswith",
    "endswith",
    "index",
    "find",
    "count",
    "sort",
    "reverse",
    "copy",
    "update",
    "clear",
    "add",
    "remove",
    "discard",
    "intersection",
    "union",
    "difference",
    "symmetric_difference",
    "isdisjoint",
    "issubset",
    "issuperset",
    "get",
    "items",
    "keys",
    "values",
    "copy",
    "update",
    "clear",
    "add",
    "remove",
    "discard",
    "intersection",
    "union",
    "difference",
    "symmetric_difference",
    "isdisjoint",
    "issubset",
    "issuperset",
    "get",
    "items",
    "keys",
    "values",
    "assert",
    "raise",
    "try",
    "except",
    "finally",
    "with",
    "as",
    "pass",
    "continue",
    "break",
    "return",
    "yield",
    "global",
    "nonlocal",
    "del",
    "import",
    "from",
    "as",
    "class",
    "def",
    "lambda",
    "return",
    "yield",
    "global",
    "nonlocal",
    "del",
    "import",
    "from",
    "as",
    "class",
    "def",
    "lambda",
]
all_words=key+common_html_tags+common_python_functions

#common code function 
def sum():
    n1=int(input("enter first number"))
    n2=int(input("enter second number"))
    sum=n1+n2
    print(sum)

if __name__ == "__main__":
    pass
